ucbgradedists/core/urls.py
from django.conf.urls import include, url
from tastypie.api import Api
from core.api.resources import *

v1_api = Api(api_name='v1')
v1_api.register(TermResource())
v1_api.register(SubjectResource())
v1_api.register(CourseResource())
v1_api.register(SectionResource())
v1_api.register(GradeResource())

urlpatterns = [
    url(r'^api/', include(v1_api.urls)),
]

ucbgradedists/search/urls.py
from django.conf.urls import url

from search.views import *

urlpatterns = [
    url(r'^$',
        Home.as_view(), name='home'),
    url(r'^division/(?P<division>.*)/$',
        DivisionView.as_view(), name='division'),
    url(r'^discipline/(?P<discipline>.*)/$',
        DisciplineDetail.as_view(), name='discipline'),
    url(r'^subject/(?P<subject>.*)/$',
        SubjectDetail.as_view(), name='subject'),
    url(r'^course/(?P<pk>.*)/$',
        CourseDetail.as_view(), name='course'),
]

ucbgradedists/core/models.py
import numpy as np
import re
from collections import Counter
from functools import cmp_to_key

from core import utils
from django.db import models
from django.db.models import Sum
from django.template.defaultfilters import slugify
from django.utils.functional import cached_property
from django_extensions.db.fields import json

course_num_pattern = re.compile('[A-Za-z]*([0-9]+)[A-Za-z]*')

class Term(models.Model):
    SPRING = 0
    SUMMER = 1
    FALL = 2
    SEASON_CHOICES = (
        (SPRING, "Spring"),
        (SUMMER, "Summer"),
        (FALL, "Fall"),
    )
    season = models.IntegerField(choices=SEASON_CHOICES)
    year = models.IntegerField()

    def __unicode__(self):
        return "{0} {1}".format(self.get_season_display(), self.year)

    class Meta:
        ordering = ['year', 'season']

class DivisionSet(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField(default='')
    # data is a json field consisting exactly of
    # { 'divisions' : [ list of divisions ] }
    data = json.JSONField()

    def __unicode__(self):
        return self.name

    @property
    def divisions_verbose(self):
        return [Course.DIVISION_CHOICE_DICT[div] for div in self.data['divisions']]

    @property
    def divisions_str(self):
        return ', '.join(self.divisions_verbose)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(DivisionSet, self).save(*args, **kwargs)


class Discipline(models.Model):
    """
    A category to which multiple subjects belong, such as natural
    science or arts and humanities.
    """
    name = models.CharField(max_length=60)
    slug = models.SlugField(default='')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Discipline, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']


class Subject(models.Model):
    """
    A single academic subject, such as mathematics or French.
    """
    name = models.CharField(max_length=256)
    canonical = models.CharField(max_length=256, null=True)
    discipline = models.ForeignKey(Discipline, null=True)
    slug = models.SlugField(default='')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Subject, self).save(*args, **kwargs)  


class Stats(models.Model):
    """
    An abstract base class to hold statistics about a
    subject or discipline.
    """

    division_set = models.ForeignKey(DivisionSet)
    letter_grades = models.IntegerField(default=0)
    mean = models.FloatField(null=True)
    stdev = models.FloatField(null=True)
    distribution = json.JSONField(null=True)
    my_rank = models.IntegerField(default=0)
    rank_count = models.IntegerField(default=0)

    class Meta:
        abstract = True

    @property
    def formatted_distribution(self):
        return utils.format_distribution(self.distribution, self.letter_grades)


class DivisionStats(Stats):
    """
    Holds division-wide stats.
    """


class DisciplineStats(Stats):
    """
    Holds statistics about a discipline for a particular division.
    """

    discipline = models.ForeignKey(Discipline)

    def __unicode__(self):
        return '{}: {}'.format(self.discipline.name, self.division_set.name)

class SubjectStats(Stats):
    """
    Holds statistics about a subject for a particular division.
    """

    subject = models.ForeignKey(Subject)

    def __unicode__(self):
        return '{}: {}'.format(self.subject.name, self.division_set.name)

class Course(models.Model):
    """
    A single course belonging to a single division, with
    many sections offered over multiple terms.
    """
    LOWER = 0
    UPPER = 1
    GRADUATE = 2
    TEACHING = 3
    PROFESSIONAL = 4
    MASTERS = 5
    DOCTORAL = 6
    OTHER = 7
    DIVISION_CHOICES = (
        (LOWER, "Lower Division"),
        (UPPER, "Upper Division"),
        (GRADUATE, "Graduate"),
        (TEACHING, "Teaching"),
        (PROFESSIONAL, "Professional"),
        (MASTERS, "Master's Exam"),
        (DOCTORAL, "Doctoral Exam"),
        (OTHER, "Other")
    )
    DIVISION_CHOICE_DICT = dict(DIVISION_CHOICES)

    subject = models.ForeignKey(Subject)
    title = models.TextField()
    number = models.CharField(max_length=10)
    num_numerical_part = models.IntegerField(null=True)
    division = models.IntegerField(choices=DIVISION_CHOICES, default=OTHER)

    # Stats
    distribution = json.JSONField(null=True)
    letter_grades = models.IntegerField(default=0)
    mean = models.FloatField(null=True)
    stdev = models.FloatField(null=True)

    def __unicode__(self):
        return "{0} {1}".format(self.subject, self.number)

    @property
    def formatted_distribution(self):
        return utils.format_distribution(self.distribution, self.letter_grades)

    def save(self, *args, **kwargs):
        m = course_num_pattern.match(self.number)
        if m:
            self.num_numerical_part = int(m.group(1))
            if self.num_numerical_part < 100:
                self.division = self.LOWER
            elif self.num_numerical_part < 200:
                self.division = self.UPPER
            elif self.num_numerical_part < 300:
                self.division = self.GRADUATE
            elif self.num_numerical_part < 400:
                self.division = self.TEACHING
            elif self.num_numerical_part < 500:
                self.division = self.PROFESSIONAL
            elif self.num_numerical_part == 601:
                self.division = self.MASTERS
            elif self.num_numerical_part == 602:
                self.division = self.DOCTORAL
            else:
                self.division = self.OTHER
        else:
            self.division = self.OTHER
        super(Course, self).save(*args, **kwargs)

    class Meta:
        ordering = ['subject', 'num_numerical_part', 'number']


class Section(models.Model):
    """
    A particular term's offering of a course, with a unique CCN.
    """
    course = models.ForeignKey(Course)
    term = models.ForeignKey(Term)
    number = models.CharField(max_length=10)
    instructor = models.CharField(max_length=1024)
    ccn = models.CharField(max_length=5, verbose_name="CCN")

    # Stats
    distribution = json.JSONField(null=True)
    letter_grades = models.IntegerField(default=0)
    mean = models.FloatField(null=True)
    stdev = models.FloatField(null=True)

    def __unicode__(self):
        return "{0}-{1} ({2})".format(self.course, self.number, self.term)

    class Meta:
        ordering = ['term', 'number']


class Grade(models.Model):
    """
    A type of grade, for example, A+ or PASS.
    """
    name = models.CharField(max_length=20)
    letter = models.BooleanField(default=False)
    points = models.FloatField(null=True, blank=True)

    def __unicode__(self):
        return self.name

class GradeCountManager(models.Manager):
    use_for_related_fields = True

    def in_grade_order(self, *args, **kwargs):
        qs = self.get_queryset().filter(*args, **kwargs)
        return sorted(qs, key = cmp_to_key(cmp_gc), reverse = True)

class GradeCount(models.Model):
    section = models.ForeignKey(Section)
    grade = models.ForeignKey(Grade)
    count = models.IntegerField()

    def __unicode__(self):
        return "GradeCount({0}, {1})".format(self.section, self.grade)

    objects = GradeCountManager()

def grade_order_key(grade_name):
    ordering = ['A+', 'A', 'A-', 'B+', 'B', 'B-',
                'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F',
                'High Honors', 'Honors',
                'Pass', 'Pass Conditional',
                'Credit', 'Satisfactory',
                'No Credit', 'Not Pass', 'Unsatisfactory']
    if grade_name not in ordering:
        return -1
    return ordering.index(grade_name)

def cmp_grade(grade1, grade2):
    """Return 0 for equal grades, 1 if grade1 > grade2, or -1 if grade1 < grade2."""
    if grade1 == grade2:
        return 0
    elif grade1.letter and not grade2.letter:
        return 1
    elif grade2.letter and not grade1.letter:
        return -1
    else:
        idx1 = grade_order_key(grade1.name)
        idx2 = grade_order_key(grade2.name)
        if idx1 == idx2:
            return 0
        elif idx1 < idx2:
            return 1
        else:
            return -1

def cmp_gc(gc1, gc2):
    return cmp_grade(gc1.grade, gc2.grade)

ucbgradedists/search/models.py
from django.db import models

# Create your models here.

ucbgradedists/search/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, RedirectView
import json

from core import utils
from core.models import Term, DivisionSet, Subject, SubjectStats, \
                        Course, Section, Grade, GradeCount, \
                        Discipline, DisciplineStats

class Home(TemplateView):
    """
    Site homepage.
    """
    template_name = 'search/home.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['divisions'] = DivisionSet.objects.all()

        division = DivisionSet.objects.get(slug='undergraduate')

        context['disciplines'] = DisciplineStats.objects.filter(division_set=division).order_by('mean')
        context['hardest_subjects'] = SubjectStats.objects.filter(division_set=division).filter(letter_grades__gte=1000).order_by('mean')[0:10]
        context['easiest_subjects'] = SubjectStats.objects.filter(division_set=division).filter(letter_grades__gte=1000).order_by('-mean')[0:10]
        context['hardest_classes'] = Course.objects.filter(division__in=[0,1]).filter(letter_grades__gte=1000).order_by('mean')[0:10]
        context['easiest_classes'] = Course.objects.filter(division__in=[0,1]).filter(letter_grades__gte=1000).order_by('-mean')[0:10]
        return context


class DivisionView(ListView):
    """
    A list of subjects in a particular division.
    """
    template_name = 'search/division.html'

    def get_queryset(self):
        self.division_set = get_object_or_404(DivisionSet,
            slug=self.kwargs['division'])
        return SubjectStats.objects.filter(division_set=self.division_set) \
                .filter(letter_grades__gte=500).order_by('mean')

    def get_context_data(self, **kwargs):
        context = {}
        courses = []
        for stat in self.get_queryset():
            info = {}
            info['sub'] = stat.subject.name
            info['slug'] = stat.subject.slug
            info['discipline'] = stat.subject.discipline.name
            info['discipline_slug'] = stat.subject.discipline.slug
            info['avg'] = stat.mean
            info['grade'] = utils.lettergrade(stat.mean)
            info['std'] = stat.stdev
            info['num'] = stat.letter_grades
            info['dist'] = stat.formatted_distribution

            courses.append(info)

        context['data'] = json.dumps(courses)
        context['name'] = self.division_set.name

        return context


class SubjectDetail(DetailView):
    """
    A single subject.
    """
    model = Subject
    template_name = 'search/subject.html'
    slug_url_kwarg = 'subject'


class DisciplineDetail(DetailView):
    """
    A single discipline.
    """
    model = Discipline
    template_name = 'search/discipline.html'
    slug_url_kwarg = 'discipline'


class CourseDetail(DetailView):
    """
    A single course.
    """
    model = Course
    template_name = 'search/course.html'

ucbgradedists/templates/search/course.html
{% extends "dt_base.html" %}
{% load humanize %}
{% load mathfilters %}
{% load gradefilters %}

{% block subtitle %}
{{ course }}
{% endblock subtitle %}

{% block content %}

    <h1><a href="{% url 'subject' course.subject.slug %}">{{ course.subject }}</a> {{ course.number }}</h1>

    <hr>

    <div class="info">
      <div class="stats">
        <ul>
          <li class="main-grade">{{ course.mean|lettergrade }}</li>
          <li>{{ course.mean|floatformat:2 }}<span>Average</span></li>
          <li>{{ course.stdev|floatformat:2 }}<span>St. Dev.</span></li>
          <li>{{ course.letter_grades|intcomma }}<span>Grades</span></li>
        </ul>
      </div>

      <div class="histogram" id="distribution"></div>
    </div>

    <hr>


<script>
    $(document).ready(function() {
        var data = {{ course.formatted_distribution|safe }}
        gradeHistogram(data, '#distribution')

    });
</script>
{% endblock content %}

ucbgradedists/templates/search/discipline.html
{% extends "dt_base.html" %}
{% load humanize %}
{% load mathfilters %}
{% load gradefilters %}
{% load staticfiles %}

{% block subtitle %}
{{ subject }} ({{ division_set.name }})
{% endblock subtitle %}

{% block content %}
<div class="discipline">
    <h1>{{ discipline.name }}</h1>    

    <ul class="accordion-tabs-minimal">
      {% for stats in discipline.disciplinestats_set.all %}
      {% if stats.letter_grades > 0 %}
       <li class="tab-header-and-content">
        <a href="#" class="tab-link">{{ stats.division_set.name }}</a>
        <div class="tab-content">
          <div class="info">
            <div class="stats">
              <ul>
                <li class="main-grade">{{ stats.mean|lettergrade }}</li>
                <li>{{ stats.mean|floatformat:2 }}<span>Average</span></li>
                <li>{{ stats.stdev|floatformat:2 }}<span>St. Dev.</span></li>
                <li>{{ stats.letter_grades|intcomma }}<span>Grades</span></li>
              </ul>
            </div>

            <div class="histogram" id="distribution-{{ stats.division_set.slug }}"></div>
          </div>

        </div>
      </li>
      {% endif %}
      {% endfor %}
    </ul>

    <hr> 

    <h2>Subjects</h2>

    <table>
    {% for subject in discipline.subject_set.all %}
    <tr>
      <td><a href="{% url 'subject' subject.slug %}">{{ subject.name }}</a></td>
    </tr>
    {% endfor %}
    </table>
    
</div>

<script>
$(document).ready(function () {
  // Render histograms
  {% for stats in discipline.disciplinestats_set.all %}
    (function() {
      var data = {{ stats.formatted_distribution|safe }}
      gradeHistogram(data, '#distribution-{{ stats.division_set.slug }}')
    })();
  {% endfor %}

  // Set up tabs
  $('.accordion-tabs-minimal').each(function(index) {
    $(this).children('li').first().children('a').addClass('is-active').next().addClass('is-open').show();
  });
  $('.accordion-tabs-minimal').on('click', 'li > a.tab-link', function(event) {
    if (!$(this).hasClass('is-active')) {
      event.preventDefault();
      var accordionTabs = $(this).closest('.accordion-tabs-minimal');
      accordionTabs.find('.is-open').removeClass('is-open').hide();

      $(this).next().toggleClass('is-open').toggle();
      accordionTabs.find('.is-active').removeClass('is-active');
      $(this).addClass('is-active');
    } else {
      event.preventDefault();
    }
  });
});
</script>

{% endblock content %}

ucbgradedists/templates/search/division_choice.html
{% extends "dt_base.html" %}

{% block subtitle %}
Divisions
{% endblock subtitle %}

{% block content %}
<div class="col-1-1">
  <div class="content">
    <h1>Division Sets</h1>
    <table id="divisionsets" class="display responsive nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Set</th>
          <th>Divisions</th>
        </tr>
      </thead>
      <tbody>
{% for divset in object_list %}
        <tr>
          <td>
            <a href="{% url 'div-subject-list' divset.id %}">
              {{ divset.name }}
            </a>
          </td>
          <td>
            {{ divset.divisions_str }}
          </td>
        </tr>
{% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
    $(document).ready(function() {
        $('#divisionsets').DataTable( {
            "order": [],
            "columnDefs": [
                { "orderable": false, "targets": 1 }
            ],
            "paging": false
        } );
    } );
</script>
{% endblock content %}

ucbgradedists/templates/search/home.html
{% extends "base.html" %}
{% load mathfilters %}

{% block content %}
<div class="home">

<div class="top">
  <h1>Grades</h1>
  <p class="byline">By Sahil Chinoy and Ronald Kwan</p>
  <p class="date">November 29, 2015</p>

  <br> 
  
  <p>The Daily Californian sifted through eight years of UC Berkeley grades, looking for the most difficult classes, departments and academic disciplines.</p>
</div>

<hr>

<div class="wrapper">
  <div class="prompt">
    <p class="title">Read the story</p>
    <p>Title of story goes here</p>
  </div>

  <div class="prompt">
    <p class="title">Explore the data</p>
    <p>Browse all subjects, or explore the hardest courses and professors. </p>
  </div>

  <div class="prompt">
    <p class="title">Build an app</p>
    <p>The code for our analysis is open-source. Use it for your own app or investigation.</p>
  </div>
</div>

<hr>

<div class="wrapper">
<div class="column">
  <h2>By division</h2>
  <table>
  {% for division in divisions %}
  <tr>
  <td>
    <a href="{% url 'division' division.slug %}">{{ division.name }}</a>
  </td>
  </tr>
  {% endfor %}
  </table>

  <h2>By discipline</h2>
  <table>
   <thead>
    <tr>
      <th class="title">Discipline</th>
      <th class="figure">Average</th>
    </tr>
  </thead>
  {% for stat in disciplines %}
  <tr>
  <td class="title">
    <a href="{% url 'discipline' stat.discipline.slug %}">{{ stat.discipline.name }}</a>
  </td>
  <td class="figure">
    {{ stat.mean|floatformat:"2" }}
  </td>
  </tr>
  {% endfor %}
  </table>
</div>

<div class="column">
  <h2>Hardest subjects</h2>
  <table>
  <thead>
    <tr>
      <th class="title">Subject</th>
      <th class="figure">Average</th>
    </tr>
  </thead>
  {% for stat in hardest_subjects %}
  <tr>
  <td class="title">
    <a href="{% url 'subject' stat.subject.slug %}">{{ stat.subject.name }}</a>
  </td>
  <td class="figure">
    {{ stat.mean|floatformat:"2" }}
  </td>
  </tr>
  {% endfor %}
  </table>

  <h2>Easiest subjects</h2>
  <table>
  <thead>
    <tr>
      <th class="title">Subject</th>
      <th class="figure">Average</th>
    </tr>
  </thead>
  {% for stat in easiest_subjects %}
  <tr>
  <td class="title">
    <a href="{% url 'subject' stat.subject.slug %}">{{ stat.subject.name }}</a>
  </td>
  <td class="figure">
    {{ stat.mean|floatformat:"2" }}
  </td>
  </tr>
  {% endfor %}
  </table>

</div>

<div class="column">
  <h2>Hardest classes</h2>
  <table>
  <thead>
    <tr>
      <th class="title">Class</th>
      <th class="figure">Average</th>
    </tr>
  </thead>
  {% for class in hardest_classes %}
  <tr>
  <td class="title">
    <a href="{% url 'course' class.id %}">{{ class }}</a>
  </td>
  <td class="figure">
    {{ class.mean|floatformat:"2" }}
  </td>
  </tr>
  {% endfor %}
  </table>

  <h2>Easiest classes</h2>
  <table>
  <thead>
    <tr>
      <th class="title">Class</th>
      <th class="figure">Average</th>
    </tr>
  </thead>
  {% for class in easiest_classes %}
  <tr>
  <td class="title">
    <a href="{% url 'course' class.id %}">{{ class }}</a>
  </td>
  <td class="figure">
    {{ class.mean|floatformat:"2" }}
  </td>
  </tr>
  {% endfor %}
  </table>
</div>

</div>

</div>
{% endblock content %}

ucbgradedists/templates/search/section_detail.html
{% extends "base.html" %}

{% block subtitle %}
{{ section }}
{% endblock subtitle %}

{% block content %}
<h1>{{ section }}</h1>
<div class="col-1-3">
  <div class="content">
    <h2>Information/Statistics</h2>
    <table cellspacing="0" width="100%">
      <tr>
        <th>Instructor(s)</th>
        <td>{{ section.instructor }}</td>
      </tr>
      <tr>
        <th>Median</th>
        <td>{{ section.grade_median|floatformat:2|default:"N/A" }}</td>
      </tr>
      <tr>
        <th>Mean</th>
        <td>{{ section.grade_average|floatformat:2|default:"N/A" }}</td>
      </tr>
      <tr>
        <th>Standard Deviation</th>
        <td>{{ section.grade_stdev|floatformat:2|default:"N/A" }}</td>
      </tr>
      <tr>
        <th>Letter Grades</th>
        <td>{{ section.letter_grades }} of {{ section.total_grades }}</td>
      </tr>
    </table>
  </div>
</div>
<div class="col-2-3">
  <div class="content">
    <h2>Grade Distribution</h2>
    <table>
      <tbody>
    {% for gc in grade_counts %}
        <tr>
          <td>{{ gc.grade }}</td>
          <td>{{ gc.count }}</td>
        </tr>
    {% empty %}
        <tr>
          <td>N/A</td>
          <td>N/A</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

ucbgradedists/templates/search/subject.html
{% extends "dt_base.html" %}
{% load humanize %}
{% load mathfilters %}
{% load gradefilters %}

{% block subtitle %}
{{ subject }} ({{ division_set.name }})
{% endblock subtitle %}

{% block content %}
<div class="subject">
    <h1>{{ subject }}</h1>
    <span class="discipline-label"><a href="{% url 'discipline' subject.discipline.slug %}">{{ subject.discipline.name }}</a></span>

    <ul class="accordion-tabs-minimal">
      {% for stats in subject.subjectstats_set.all %}
      {% if stats.letter_grades > 0 %}
       <li class="tab-header-and-content">
        <a href="#" class="tab-link">{{ stats.division_set.name }}</a>
        <div class="tab-content">
          <div class="info">
            <div class="stats">
              <ul>
                <li class="main-grade">{{ stats.mean|lettergrade }}</li>
                <li>{{ stats.mean|floatformat:2 }}<span>Average</span></li>
                <li>{{ stats.stdev|floatformat:2 }}<span>St. Dev.</span></li>
                <li>{{ stats.letter_grades|intcomma }}<span>Grades</span></li>
                <li>{{ stats.my_rank }} of {{ stats.rank_count }}<span>Rank</span></li>
              </ul>
            </div>
            <div class="histogram" id="distribution-{{ stats.division_set.slug }}"></div>
          </div>

        </div>
      </li>
      {% endif %}
      {% endfor %}
    </ul>


    <hr> 


    <table id="courses-table" class="responsive nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Course</th>
          <th>Average</th>
          <th>St. Dev.</th>
          <th>Grades</th>
        </tr>
      </thead>
      <tbody>
      {% for course in subject.course_set.all %}
      {% if course.letter_grades > 10 %}
        <tr>
          <td>
            <a href="{% url 'course' course.id %}">
              {{ course }}
            </a>
          </td>
          <td>
            {{ course.mean|floatformat:2 }}
          </td>
          <td>
            {{ course.stdev|floatformat:2 }}
          </td>
          <td>
            {{ course.letter_grades|intcomma }}
          </td>
        </tr>
      {% endif %}
      {% endfor %}
      </tbody>
    </table>

</div>

<script>
$(document).ready(function () {
  // Render histograms
  {% for stats in subject.subjectstats_set.all %}
    (function() {
      var data = {{ stats.formatted_distribution|safe }}
      gradeHistogram(data, '#distribution-{{ stats.division_set.slug }}')
    })();
  {% endfor %}

  // Set up tabs
  $('.accordion-tabs-minimal').each(function(index) {
    $(this).children('li').first().children('a').addClass('is-active').next().addClass('is-open').show();
  });
  $('.accordion-tabs-minimal').on('click', 'li > a.tab-link', function(event) {
    if (!$(this).hasClass('is-active')) {
      event.preventDefault();
      var accordionTabs = $(this).closest('.accordion-tabs-minimal');
      accordionTabs.find('.is-open').removeClass('is-open').hide();

      $(this).next().toggleClass('is-open').toggle();
      accordionTabs.find('.is-active').removeClass('is-active');
      $(this).addClass('is-active');
    } else {
      event.preventDefault();
    }
  });

  // Set up the list of courses 
  $('#courses-table').DataTable( {
        "order": [],
        "paging": false,
        "searching": false,
        "info": false,
    } );
});
</script>

{% endblock content %}

ucbgradedists/templates/search/subject_list.html
{% extends "dt_base.html" %}
{% load mathfilters %}

{% block subtitle %}
Subjects
{% endblock subtitle %}

{% block content %}
<div class="col-1-1">
  <div class="content">
    <h1>Subjects ({{ divset.name }})</h1>
    <table id="subjects" class="display responsive nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Subject</th>
          <th>Median</th>
          <th>Mean</th>
          <th>St. Dev.</th>
          <th>Grades</th>
          <th>% Letter</th>
        </tr>
      </thead>
      <tbody>
{% for stats in object_list %}
        <tr>
          <td>
            <a href="{% url 'div-subject-course-list' stats.division_set.id stats.subject.id %}">
              {{ stats.subject.name }}
            </a>
          </td>
          <td>
            {{ stats.grade_median|floatformat:2|default:"N/A" }}
          </td>
          <td>
            {{ stats.grade_average|floatformat:2|default:"N/A" }}
          </td>
          <td>
            {{ stats.grade_stdev|floatformat:2|default:"N/A" }}
          </td>
          <td>
            {{ stats.total_grades }}
          </td>
          <td>
{% if stats.total_grades > 0 %}
            {{ stats.letter_grades|div:stats.total_grades|mul:100|floatformat:0 }}
{% else %}
            N/A
{% endif %}
          </td>
        </tr>
{% empty %}
        <tr>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
        </tr>
{% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
    $(document).ready(function() {
        $('#subjects').DataTable( {
            "paging": false
        } );
    } );
</script>
{% endblock content %}